export const PERMISSIONS = {
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_WORKSPACES: "MANAGE_WORKSPACES",
  MANAGE_PROJECTS: "MANAGE_PROJECTS",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  MANAGE_NOTIFICATIONS: "MANAGE_NOTIFICATIONS",
};